server:
  port: ${PORT:5004}

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JJaraM/blog-microservice-config-server.git

  security:
    user:
      name: root
      password: s3cr3t