shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED

logging:
  file:
    path: "logs"
    name: "logs/client.log"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: "logs/client.log"
