spring:

  shell:
    interactive:
      enabled: false

  cors:
    allowed-origin: >
      https://jonathanjaramorales.herokuapp.com,
      https://blog-eureka-server.herokuapp.com,
      http://jonathanjaramorales.herokuapp.com,
      http://blog-eureka-server.herokuapp.com
