server:
  port: ${PORT:5001}

spring:
  redis:
    channels:
      channel-tag-add: channel_tag_add
      channel-tag-remove: channel_tag_remove

  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
springdoc:
  version: '@springdoc.version@'

# security:
#   oauth2:
#     resourceserver:
#       jwt:
#         issuer-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog
#         jwk-set-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3600
    lease-expiration-duration-in-seconds: 3600
    hostname: localhost
  client:
    initial-instance-info-replication-interval-seconds: 3600
    instance-info-replication-interval-seconds: 3600
    registry-fetch-interval-seconds: 3600
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://blog-eureka-server.herokuapp.com/eureka/

discovery:
  uri: https://jjara-discovery.herokuapp.com/v1/discovery/